blog/urls.py
from django.urls import path

from .views import Blog, PostDetail, PostList, SinglePost

app_name = 'blog'

urlpatterns = [
        path('', Blog.as_view(), name='blog'),
        path('api/post/<slug:slug>', SinglePost.as_view(), name='single_post_api'),
        path('api/post', PostList.as_view(), name='api-postlist'),
        path('<slug:slug>/', PostDetail.as_view(), name='post')
        ]

myportfolio/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('portfolio.urls', namespace='portfolio')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
]

portfolio/urls.py
from django.urls import path

from .views import Home, Portfolio, About, emailView, successView

app_name = 'porfolio'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('contact/', emailView, name='contact'),
    path('emailsent/', successView, name='success'),
    path('portfolio/', Portfolio.as_view(), name='portfolio'),
    path('about/', About.as_view(), name='about'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import mark_safe
from django.utils.text import slugify
from markdown import markdown

class Post(models.Model):
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=256)
    category = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(max_length=20, unique=True, blank=True, null=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)

        super(Post, self).save(*args, **kwargs)

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'Looking for a junior developer? Need a cool website? Let\'s get in touch!'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
        )

blog/views.py
from django.utils import timezone
from .models import Post
from django.views.generic import ListView, DetailView
from .serializers import PostSerializer
from rest_framework import generics

class Blog(ListView):
    model = Post
    template_name = 'portfolio/blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_posts'] = Post.objects.order_by('-published_date')
        return context

class PostDetail(DetailView):
    model = Post
    template_name = 'portfolio/post.html'
    slug_url_kwarg = 'slug'

class PostList(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class SinglePost(generics.RetrieveAPIView):
    lookup_field = 'slug'
    queryset = Post.objects.all()
    serializer_class = PostSerializer

portfolio/views.py
from django.core.mail import BadHeaderError, EmailMessage
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.views.generic import TemplateView
import requests

class Home(TemplateView):
    template_name = 'portfolio/index.html'

class Contact(TemplateView):
    template_name = 'portfolio/contact.html'

class Blog(TemplateView):
    template_name = 'portfolio/blog.html'

class Portfolio(TemplateView):
    template_name = 'portfolio/portfolio.html'

    def get_context_data(self, **kwargs):
        try:
            url = 'https://api.github.com/users/yannickleroux'
            response = requests.get(url)
            user = response.json()

            url_repos = 'https://api.github.com/users/yannickleroux/repos'
            response = requests.get(url_repos)
            repos = response.json()

            context = super(Portfolio, self).get_context_data(**kwargs)
            context['user'] = user
            context['repos'] = repos
            return context

        except requests.exceptions.RequestException as e:
            print (e) 




class About(TemplateView):
    template_name = 'portfolio/about.html'

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            to = ['yannick.leroux971@gmail.com']
            subject = "I got a message from yannick-dev"
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                context = {
                        'name': name,
                        'from_email': from_email,
                        'message': message
                        }
                message = render_to_string('portfolio/email/email.txt',
                        context)
                EmailMessage(subject, message, to=to,
                        from_email=from_email).send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('portfolio:success')
    return render(request, "portfolio/contact.html", {'form': form})

def successView(request):
    return render(request, "portfolio/success.html")

templates/portfolio/about.html
{% extends "portfolio/base.html" %}
{% load static %}
{% block title %} Yannick Le Roux - About me {% endblock title %}
{% block content %}
<div class="container">
	<div class="intro">
   <div class="section-blockquote mt-5">
		<blockquote>
			<p>Teaching myself coding on a daily basis since May 2017, I enjoy solving real-life problems with what I learned.
			</br> For example, I started automating time consuming tasks at my current job.</p>
		</blockquote>
	</div>
	<p><strong>My Objective:</strong> Get a first developer job in 2018.</p>
	</div>
	<hr>
</div>
<div class="container">
	<div class="container my-5">
		<div class="text-center"><a href="http://yannick-dev.com/static/files/Resume-v10.pdf" target="_blank" class="btn btn-primary btn-lg hero-button anim-button mb-4" id="download" >Download my Resume</a></div>

		<br/>
		<p>After working for ten years as a sound engineer and DJ in the music industry, I felt a desire to switch career early 2017.</br>

		I remember that as a kid and then a teenager, I loved to create small scripts on my Atari STE, or even hack into some games. I just didn't know at that time if I had what it would take to, one day, become a professional developer.</p>

		<p>Then I discovered the impressive range and quality of online content designed to teach people, like me, how to write code.</br>
    I asked some informed people for advice and was told to give Python a try.</p>

		<p>I quickly completed a first course created by MIT, <em>Introduction to Computer Science and Python</em>, and
		<a href="https://courses.edx.org/certificates/094c7498fb13491b95ae05ff29ab9117" target="_blank">achieved a passing grade.</a></br>

		I enjoyed the course so much I became hooked on learning more about how to code.</p>


		<div class="clock">
      <div class="clock-face">
        <div class="hand hour-hand"></div>
        <div class="hand min-hand"></div>
        <div class="hand second-hand"></div>
      </div>
    </div>
<h4 class="text-center mb-5"><i class="fa fa-quote-left"></i> Time to get my first developer job! <i class="fa fa-quote-right"></i></h4>


		<p>The first personal projects I undertook were driven by the idea of making my current job easier. <a href="https://github.com/YannickLeRoux/mp3_organizer" target="_blank">Organizing the music files</a> in
		my laptop or <a href="https://github.com/YannickLeRoux/DMC_Chart_Parser" target="_blank">reading through tons of blog articles and charts</a> to collect good tracks to play, could be very boring and repetitive. These things, I felt, could definitely be helped by coding.</br></br>

		For several years, I had been building websites using WordPress, but once I knew how to code, I wanted to know how to build a website from scratch.</p>

		<p>Well, it so happens that Python is good at that too! As I was already familiar with HTML and CSS, I got into <a href="https://www.udemy.com/certificate/UC-5PRSEYVI/" target="_blank">Django</a> to learn to create the back-end. </br>
My first project was to create a <a href="http://receipts-organizer.herokuapp.com/" target="_blank">receipts organizer</a> app, one that could scan receipts and keep them organized in a database. I still have to make some improvements to it (i.e. the facility to scan with a phone, design, security, etc.,) but anybody can sign up for an account and import documents already scanned.</p>

		<p>I next decided to learn JavaScript, following the <a href="https://courses.edx.org/certificates/ee19337ad1df495cb24f91648532eac3" target="_blank">University of Pennsylvania online course</a>,  as I believe it is essential for Web Development.</p>

		<p>Django is amazing but it's sometimes too much boilerplate for <a href="https://twitterpie.herokuapp.com/" target="_blank">very small apps like this one</a>, so I learned how to use Flask as well.</p>

		<p>These days, I continue to dive deeper into programming, extending my front-end knowledge learning <strong>React JS</strong> (web app currently in development), and deployment tools like Docker. I am also improving my ability to deploy my apps on a Linux server as I firmly believe <strong>Web apps belong to the Web !</strong>
		</p>
	    </div>
	</div>

</div>

{% endblock %}

{% block javascript %}
 <script src="{% static "js/clock.js" %}"></script>
{% endblock javascript %}

templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23484726-4"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-23484726-4');
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Yannick Le Roux - Web & Software Development - San Diego{% endblock title %}</title>

  <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700i,800,900">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
  <link rel="stylesheet" href="{% static "css/Contact-Form-Clean.css" %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
  <link rel="stylesheet" href="{% static "css/Navigation-Clean.css" %}">
  <link rel="stylesheet" href="{% static "css/Paralax-Hero-Banner.css" %}">
  <link rel="stylesheet" href="{% static "css/Team-Boxed.css" %}">
  <link rel="stylesheet" href="{% static "css/vim.css" %}">
  <link rel="stylesheet" href="{% static "css/Footer-Dark.css" %}">
  <link rel="stylesheet" href="{% static "css/Portfolio.css" %}">
  <link rel="stylesheet" href="{% static "fonts/font-awesome.min.css" %}">
  <link rel="shortcut icon" href="{% static "img/favicon.ico" %}"> {% block addstyle %} {% endblock addstyle %}
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>

{% block body %}

<body>
  <div class="page"></div>
  <div>
    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
      <div class="container">
        <a class="navbar-brand" href="{% url 'portfolio:home' %}">Yannick Le Roux </a>
        <span id="tagline" class="navbar-brand">
          <i class="fa fa-laptop" style="color: white;"></i>
          <small> Developer in the making</small>
        </span>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav ml-auto">

            {% with url_name=request.resolver_match.url_name %}
            <li class="nav-item" role="presentation">
              <a class="nav-link {% if url_name == 'about' %}active{% endif %}" href="{% url 'portfolio:about' %}">About me</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link {% if url_name == 'portfolio' %}active{% endif %}" href="{% url 'portfolio:portfolio' %}">Portfolio</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link {% if url_name == 'blog' %}active{% endif %}" href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link {% if url_name == 'contact' %}active{% endif %}" href="{% url 'portfolio:contact' %}">Hire Me</a>
            </li>

            {% endwith %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="make-space"></div>
  </div>
  <div class="content">
    {% block content %} {% endblock content %}

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/myscript.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    {% block javascript %} {% endblock javascript %}
</body>
{% endblock body %}
</div>
<div class="footer-dark">
  <footer>
    <div class="container">
      <div class="row">
        <div class="col item social">
          <a href="https://stackoverflow.com/users/8045609/yannick?tab=profile">
            <i class="fa fa-stack-overflow"></i>
          </a>
          <a href="https://twitter.com/DJ_Yanic/">
            <i class="fa fa-twitter"></i>
          </a>
          <a href="https://github.com/YannickLeRoux">
            <i class="fa fa-github"></i>
          </a>
          <a href="https://www.linkedin.com/in/yannick-le-roux/">
            <i class="fa fa-linkedin"></i>
          </a>
        </div>
      </div>
      <p class="copyright">Yannick Le Roux © 2018</p>
    </div>
  </footer>
</div>

</html>

templates/portfolio/blog.html
{% extends "portfolio/base.html" %}
{% load markdownify %}

{% block content%}
<!-- une icone carree bords arrondis avec ombre pour marquer chaque post -->
<!-- a sa droite titre et date --> 
<!-- reprendre couleur de fond de contact et faire des div blancs pour chaque post -->
<!-- voir a utiliser react -->

<div class="blog">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">My Blog</li>
</ol>
<div class="container">
  <div>
	{% if my_posts %}
  {% for post in my_posts %}
  <div class="blog-post">
    <h2><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></h2>
    <h6 style="float:right">Category: {{ post.category }}</h6>
    <h6>{{ post.published_date|date:"M d, Y" }}</h6>
    <div class="container">
      <hr>

      <div>{{ post.text|markdown|safe|truncatewords:10 }}</div>
			<a class="text-mute text-right" href="{% url 'blog:post' post.slug %}" ><i class="fa fa-arrow-circle-right"></i> Read more...</a>
    </div>
  </div>

  {% empty %}
  <h2>No Articles yet.</h2>
  </div>
</div>
</div>

{% endfor %}
{% endif %}
{% endblock %}

templates/portfolio/contact.html
{% extends "portfolio/base.html" %} 
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="contact-clean">
	<div class="container mb-5">
	<div class="row">
		<div class="col-md-4 col-sm-12 my-auto text-center">

			
			<p class="text-center"> Please let me know how I could help you! ✍️ </p>
			<p>Are you looking to add a highly motivated Junior Developer to your team ? 🙋‍♂️</p>
			<p>Do you just need a cool website? </p>

				<p class="text-center mb-2">I am looking forward to hearing from you!</p>
	  

		</div>
<div class="col-md-8 col-sm-12">

<form method="post" novalidate>
  <h2 class="text-center">Contact Form</h2>

  {% csrf_token %}

  {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}

          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}

        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">
          {{ field.help_text }}
        </small>
      {% endif %}
    </div>
  {% endfor %}
  <div class="form-group"><button class="btn btn-primary btn-lg hero-button"
      type="submit"> Send </button></div>
</form>
</div>
</div>
</div>


{% endblock %}

templates/portfolio/index.html
{% extends "portfolio/base.html" %}
{%load static %}
{% block title %}Yannick Le Roux - Home{% endblock title %}

		{% block content %}
   <div class="jumbotron hero-technology">
        <div class="container home-title-container">
				<h1 class="homepage-title">This website is deprecated.<br>Please visit the new React version.<br>Link Below.</h1>
		</div>
				<p><a class="btn btn-primary btn-lg hero-button anim-button" role="button" href="https://yannickleroux.com">Visit my new Site</a></p>
    </div>
    <div class="container mb-5">
			<div class="text-center">
				<p><em>Portfolio Website made with Love, Python & Javascript</em></p>
			</div>
			<div class="text-center">
        <i class="fa fa-laptop fa-5x mb-3" id="laptop-index"></i>
			</div>
        <p class="text-center">Hi! I am Yannick Le Roux, <strong>Software</strong> and <strong>Web</strong> developper <em>in the making</em>.</p>
        <p class="text-center">I used <strong>Python</strong> to build the back-end of this project, <strong>HTML</strong>, <strong>CSS</strong>, <strong>Javascript</strong> and <strong>Bootstrap</strong> for the Front End. </p>
				<p>I like to make any kind of applications that could make your life easier or, very humbly, make the world a better place. :)</p>
    </div>
{% endblock content %}

templates/portfolio/portfolio.html
{% extends "portfolio/base.html" %}
{% load static %}
{% block content %}



<div class="portfolio">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Websites</h2>
                <p class="text-center">Before learning to code, I used to create website using Wordpress. See some below.</p>
            </div>
            <div class="row articles">
                <div class="col-sm-6 col-md-4 item">
                  <div class="image-portfolio">
                    <a href="http://dj-newyork.com" target="_blank"><img
                    class="img-fluid" src="{% static "img/djnewyork.jpg" %}">
                    <div class="overlay">
                      <div class="text-image-portfolio">Visit →</div>
                    </div>
                    </a>
                    </div>
                    <h3 class="name">DJ-NewYork Agency</h3>
										<p class="description">Made in 2017, this website allows the user to browse the talents of this agency and ask for their availability.</p></div>

                    <div class="col-sm-6 col-md-4 item">
                      <div class="image-portfolio">
                      <a href="https://raquelleroux.com" target="_blank"><img
                      class="img-fluid" src="{% static "img/raquelleroux.jpg" %}">
                      <div class="overlay">
                          <div class="text-image-portfolio">Visit →</div>
                        </div>
                        </a>
                        </div>
                    <h3 class="name">Raquel Le Roux Yoga</h3>
                    <p class="description">I made this website in 2015. It includes some e-commerce solutions.</p></div>

                <div class="col-sm-6 col-md-4 item">
                  <div class="image-portfolio">
                  <a href="https://dj-yanic.com" target="_blank"><img
                  class="img-fluid" src="{% static "img/djyanic.jpg" %}">
                  <div class="overlay">
                      <div class="text-image-portfolio">Visit →</div>
                    </div>
                    </a>
                    </div>
                <h3 class="name">DJ Yanic</h3>
                <p class="description">I created this website in 2014 to promote my DJ activity. Designed with Wordpress.</p></div>
            </div>
        </div>
</div>

<div class="portfolio">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Web Apps</h2>
                <p class="text-center">Developed with Python and Bootstrap.</p>
            </div>
            <div class="row articles">
                <div class="col-sm-6 col-md-6 item"><div class="image-portfolio">

                 <a href="https://twitterpie.herokuapp.com/" target="_blank"><img
                    class="img-fluid" src="{% static "img/twitterpie.jpg" %}">
                    <div class="overlay">
                        <div class="text-image-portfolio">Visit →</div>
                      </div>
                      </a>
                      </div>
                    <h3 class="name">Twitter Pie</h3>
										<p class="description">Flask app that takes a Twitter handle and returns a charts for the 10 most used words in the user feed.</p></div>
                <div
                    class="col-sm-6 col-md-6 item">
                    <div class="image-portfolio">
                    <a href="http://receipts-organizer.herokuapp.com/" target="_blank"><img
                      class="img-fluid" src="{% static "img/receiptsorganizer.jpg" %}">
                      <div class="overlay">
                        <div class="text-image-portfolio">Visit →</div>
                      </div>
                      </a>
                      </div>
                      <h3 class="name">Receipts Organizer</h3>
                    <p class="description">Create a user account and upload your receipts scans to keep them organized by date and category. Work in progress.</p></div>
                   </div>
</div>


<div class="portfolio">
<div class="container">
    <div class="intro">

    <h2 class="text-center">Open Source Projects</h2>
		{% if user %}
    <p> I currently have {{ user.public_repos }} public repositories on
    GitHub:</p>
		{% else %}
		<p>Error: Can't access GitHub API</p>
		{% endif %}
    <ul class="mt-5">
		{% if repos %}
    {% for repo in repos %}
    <li class="my-3"><a href={{ repo.html_url  }}>{{ repo.name }}</a></br>
      {% if repo.description %}
      <small>{{ repo.description }}</small>
      {% endif %}
      <hr> </li>
    {% endfor %}
		{% endif %}
    </ul>

		</div>
</div>
</div>
{% endblock %}

templates/portfolio/post.html
{% extends "portfolio/base.html" %}
{% load markdownify %}

{% block content%}


<div class="blog">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:blog' %}">My Blog</a></li>
    <li class="breadcrumb-item active">{{ post.title }}</li>
</ol>
<div class="container">
  <div>
  <div class="blog-post">
    <h2>{{ post.title }}</h2>
    <h6 style="float:right">Category: {{ post.category }}</h6>
    <h6>{{ post.published_date|date:"M d, Y" }}</h6>
    <div class="container">
      <hr>

      <div>{{ post.text|markdown|safe }}</div>
    </div>
  </div>
  </div>
</div>
</div>
{% endblock %}

templates/portfolio/success.html
{% extends "portfolio/base.html" %}
{% block content %}
<div class="alert alert-success" role="alert">
	Thank you, email sent! I'll get back to you shortly.
</div>
<div class="rest-of-the-page" style="height: 440px; text-align: center;">
	<i class="fa fa-thumbs-up anim-button fa-5x"></i>
</div>
{% endblock %}